config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'medium#index'
  resources :medium, only: [:index, :show] do 
    member do 
      post 'buy'
      delete 'delete'
    end
    collection do 
      get 'movies'
      get 'tv_shows'
    end
  end

  resources :user, only: [] do 
    collection do 
      get 'media'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/medium.rb
# == Schema Information
#
# Table name: media
#
#  id             :integer          not null, primary key
#  name           :string
#  media_type     :integer
#  episode_number :integer
#  media_group_id :integer
#  description    :text
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Medium < ApplicationRecord
  belongs_to :media_group, optional: true, class_name: "MediumGroup"

  enum media_type: [:movie, :tv_show]
end

app/models/medium_group.rb
# == Schema Information
#
# Table name: medium_groups
#
#  id          :integer          not null, primary key
#  name        :string
#  season      :integer
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class MediumGroup < ApplicationRecord
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :user_media
  has_many :media, through: :user_media
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def buy(medium)
    um = UserMedium.find_or_create_by(user_id: self.id, medium_id: medium.id)
    if um.expired?
      um.touch
    end
  end

  def bought?(medium)
    um = UserMedium.find_by(user_id: self.id, medium_id: medium.id)
    um.present? and !um.expired?
  end

  def delete(medium)
    um = UserMedium.find_by(user_id: self.id, medium_id: medium.id)
    um.destroy if um.present?
  end
end

app/models/user_medium.rb
# == Schema Information
#
# Table name: user_media
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  medium_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class UserMedium < ApplicationRecord
  belongs_to :user
  belongs_to :medium

  def time_to_expire
    self.updated_at + 3.days - Time.now
  end

  def expired?
    (self.updated_at + 3.days - Time.now) < 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:home]

  def home
  end
end

app/controllers/medium_controller.rb
class MediumController < ApplicationController
  before_action :set_medium, only: [:buy, :delete, :show]

  def index
  end

  def show
  end

  def movies
    @media = Rails.cache.fetch("movies", expires_in: 1.day) do 
      Medium.movie
    end
  end

  def tv_shows
    @media = Rails.cache.fetch("tv_shows", expires_in: 1.day) do 
      Medium.tv_show
    end
  end

  def buy
    current_user.buy(@medium)
    redirect_to request.referrer
  end

  def delete
    current_user.delete(@medium)
    redirect_to request.referrer
  end

  private
  def set_medium
    @medium = Medium.find_by(id: params[:id])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def media
    @media = Rails.cache.fetch("media_#{current_user.id}", expires_in: 1.day) do 
      current_user.user_media
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def prettify_time(duration)
    milliseconds = duration % 1.second.in_milliseconds

    # duration in seconds modulus number of seconds in one minute
    seconds = (duration / 1.second) % (1.minute / 1.second)

    # duration in minutes modulus number of minutes in one hour
    minutes = (duration / 1.minute) % (1.hour / 1.minute)

    # duration in hours modulus number of hours in one day
    hours = (duration / 1.hour) % (1.day / 1.hour)

    format("%02dh:%02dm:%02ds", hours, minutes, seconds)
  end
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rosalinda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
   <% if user_signed_in? %>
    <p>
      <%= link_to "Home", medium_index_path %>
      <%= link_to "My Purchases", media_user_index_path %>
    </p>
   <% end %>
    <%= yield %>
  </body>
</html>

app/views/medium/index.html.erb
<p>
  Hello <%= current_user.email %>  
</p>


<%= link_to "Movies", movies_medium_index_path %>

<%= link_to "TV shows", tv_shows_medium_index_path %>

app/views/medium/movies.html.erb
<h1>Movies</h1>
<ul>
  <% @media.each do |medium| %>
    <p>
      <% if current_user.bought? medium %>
        <%= link_to medium.name, medium_path(medium) %> - <%= link_to "Delete", delete_medium_path(medium), method: :delete %>
      <% else %>
        <%= link_to medium.name, medium_path(medium) %> - <%= link_to "Buy", buy_medium_path(medium), method: :post %>
      <% end %>
    </p>
  <% end %>
</ul>

app/views/medium/show.html.erb
<%= @medium.name %>

<%= @medium.description %>

app/views/medium/tv_shows.html.erb
<h1>TV shows</h1>
<ul>
  <% @media.each do |medium| %>
    <p>
      <% if current_user.bought? medium %>
        <%= link_to medium.name, medium_path(medium) %> - <%= link_to "Delete", delete_medium_path(medium), method: :delete %>
      <% else %>
        <%= link_to medium.name, medium_path(medium) %> - <%= link_to "Buy", buy_medium_path(medium), method: :post %>
      <% end %>
    </p>
  <% end %>
</ul>

app/views/user/media.html.erb
<h1>Purchases</h1>
<ul>
  <% @media.each do |user_medium| %>
    <% medium = user_medium.medium %>
    <p>
      <% unless user_medium.expired? %>
        <%= medium.name %> - <%= link_to "Delete", delete_medium_path(medium), method: :delete %>
        <%= prettify_time user_medium.time_to_expire %>
      <% end %>
    </p>
  <% end %>
</ul>